import { BoundTemplateFunction } from "../template.types";
export declare var a: BoundTemplateFunction;
export declare var br: BoundTemplateFunction;
export declare var b: BoundTemplateFunction;
export declare var div: BoundTemplateFunction;
export declare var span: BoundTemplateFunction;
export declare var img: BoundTemplateFunction;
export declare var video: BoundTemplateFunction;
export declare var source: BoundTemplateFunction;
export declare var input: BoundTemplateFunction;
export declare var option: BoundTemplateFunction;
export declare var select: BoundTemplateFunction;
export declare var h1: BoundTemplateFunction;
export declare var h2: BoundTemplateFunction;
export declare var h3: BoundTemplateFunction;
