"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const template_1 = require("./template");
exports.Template = template_1.Template;
const objectStore_1 = require("./ObjectStore/objectStore");
exports.ObjectStore = objectStore_1.ObjectStore;
exports.Value = objectStore_1.Value;
const elements_1 = require("./DOM/elements");
exports.div = elements_1.div;
exports.span = elements_1.span;
exports.ul = elements_1.ul;
exports.li = elements_1.li;
exports.input = elements_1.input;
exports.b = elements_1.b;
exports.a = elements_1.a;
exports.br = elements_1.br;
exports.img = elements_1.img;
exports.video = elements_1.video;
exports.source = elements_1.source;
exports.option = elements_1.option;
exports.select = elements_1.select;
exports.h1 = elements_1.h1;
exports.h2 = elements_1.h2;
exports.h3 = elements_1.h3;
//# sourceMappingURL=index.js.map